// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    /**
     * `DIRECT_URL` quando existir: em Postgres atrás de pooler (PgBouncer no
     * Neon, por exemplo) o `migrate` precisa de uma conexão direta — pelo
     * endpoint pooled ele falha ao criar o advisory lock. Na instalação
     * on-premise a variável não existe e vale a `DATABASE_URL` de sempre.
     */
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
